config/routes.rb
Buildit::Application.routes.draw do

  get "comments/index"

  get "comments/new"

  root to: 'features#index'
  
  resources :companies
  resources :users
  resources :features do
    member { post :vote }
    resources :comments
  end
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match 'users/:id' => 'users#show', as: :user
  get "pages/home"
  get "users/show"

end

app/models/company.rb
class Company < ActiveRecord::Base
	attr_accessible :name, :website_url, :twitter_nickname, :avatar, :image_remote_url
	has_many :prioritizations
	has_many :features, :through => :prioritizations
	has_attached_file :avatar, :styles => { :small => "100x100#", :medium => "300x300#", :large => "500x500#" }, :default_url => "https://s3.amazonaws.com/featurehunt/FeatureHunt.png"  


	def image_remote_url=(url_value)
		self.avatar = URI.parse(url_value) unless url_value.blank?
		super
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all(order: 'name')
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @features = @company.features.find_with_reputation(:votes, :all, order: 'votes desc')
    # @features = @company.features.reverse
    # @features_days = Feature.find_with_reputation(:votes, :all, order: 'votes desc').group_by { |f| f.created_at.end_of_day }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company, html: { class: "form-horizontal"}) do |f| %>
<%= f.error_notification %>



<%= f.text_field :name, placeholder: "Company name", class: "new-feature", :autocomplete => :off %>

<%= f.text_field :website_url, placeholder: "Website URL", class: "new-feature", :autocomplete => :off %>

<%= f.text_field :twitter_nickname, placeholder: "twitter_handle (no @ symbol)", class: "new-feature", :id => "new-feature-description", :autocomplete => :off %>

<div class="new-feature">
	Profile picture
	<%= f.input :avatar, label: false %>
	<%= f.input :image_remote_url, label: "or enter a URL" %>
</div>

<div class="form-actions">
  <%= f.button :submit, class: "new-feature-button" %>
</div>
<% end %>

app/views/companies/edit.html.erb
 <h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="feature-date">
  Companies on Feature Hunt
</div>

<% @companies.each do |company| %>
<div class='feature-box'>
  <div class="company-index">
    <%= image_tag company.avatar(:small) %>
  </div>
  <div id="show-title">
    <a href="/companies/<%= company.id %>"><%= company.name %></a>
    <div id="show-company">
    </div>
  </div>

</div>
<% end %>

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<div class="feature-show">
	<div class="feature-header">
		<table>
			<tr>
				<td>
					<%= image_tag @company.avatar(:small) %>
				</td>
				<td>
					<div id="title" style="margin-left:20px">
						<a href="<%= @company.website_url %>" target="_blank" style="font-size: 28px"><%= @company.name %></a>
						<div id="company">
							<% @features.each do |feature| %><%= Company.find(feature.company_ids).count %><% end %> features
						</div>
						<div id="poster">

							

						</div>
					</div>
				</td>
			</tr>
		</table>
	</div>
</div>
<br>

<% @features.each do |feature| %>
<div class='feature-box'>
	<div id="upvote-box">
		<%= link_to content_tag(:i, "", class: "glyphicon glyphicon-arrow-up") + "", vote_feature_path(feature, type: "up"), method: "post" %>
		<br>
		<%= pluralize feature.reputation_for(:votes).to_i, "" %>
	</div>
	<div id="show-title">
		<a href="/features/<%= feature.id %>"><%= feature.name %></a>
		<div id="show-company">
			<% Company.find(feature.company_ids).each do |c| %> 
			<a href="/companies/<%= c.id %>" target="_blank"><%= c.name %></a>
			<% end %>
		</div>
	</div>

</div>
<% end %>

<div style="margin-top: 20px">
   <form action="/features/new">
      <input class="new-feature-button" type="submit" value="Post a feature">
  </form>
</div>