config/routes.rb
Buildit::Application.routes.draw do

  get "comments/index"

  get "comments/new"

  root to: 'features#index'
  
  resources :companies
  resources :users
  resources :features do
    member { post :vote }
    resources :comments
  end
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match 'users/:id' => 'users#show', as: :user
  get "pages/home"
  get "users/show"

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  attr_accessible :company, :description, :name, :priority, :shot1, :shot2, :shot3, :company_ids
  belongs_to :user
  validates :user_id, presence: true
  has_reputation :votes, source: :user, aggregated_by: :sum
  has_attached_file :shot1, styles: { medium: "100%"}
  has_attached_file :shot2, styles: { medium: "100%"}
  has_attached_file :shot3, styles: { medium: "100%"}
  has_many :comments, as: :commentable
  has_many :prioritizations
  has_many :companies, :through => :prioritizations
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  # GET /features
  # GET /features.json
  def index
    # @features = Feature.all
    @features = Feature.find_with_reputation(:votes, :all, order: 'votes desc')
    @features_days = Feature.find_with_reputation(:votes, :all, order: 'votes desc').group_by { |f| f.created_at.end_of_day }
    # @features_days = @features.group_by { |f| f.created_at.time }
    # @features = Feature.group_by{ |feature| feature.created_at.to_date }
    # @features = Feature.group_by_day(:created_at).count
    # @features = Feature.order("DATE(start_at)").group("DATE(start_at)").count
    # @features_by_date = Feature.group_by_day(:created_at).reverse_order.count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])
    @commentable = @feature
    @comments = @commentable.comments.reverse
    @comment = Comment.new
    @company = Company.find(@feature.company_ids)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @feature = Feature.find(params[:id])
    @feature.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, flash: { tweet_modal: true }
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = current_user.features.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = current_user.features.find(params[:id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = current_user.features.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = current_user.features.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = current_user.features.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_feature.html.erb
<div class='feature-box'>
    <div id="upvote-box">
        <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-arrow-up") + "", vote_feature_path(feature, type: "up"), method: "post" %>
        <br>
        <%= pluralize feature.reputation_for(:votes).to_i, "" %>
    </div>
    <div id="show-title">
        <a href="/features/<%= feature.id %>"><%= h truncate(feature.name, length: 65) %></a>
        <div id="show-company">
            <% Company.find(feature.company_ids).each do |c| %> 
            <a href="/companies/<%= c.id %>" target="_blank"><%= c.name %></a>
            <% end %>
        </div>
    </div>

    <!-- <div id="box-image">
        <%= image_tag User.find(feature.user_id).avatar(:medium) %>
    </div> -->

</div>




<!-- feature Modal -->
<div class="modal fade" id="feature">
    <div class="modal-dialog">
        <div class="modal-content" style="border-radius: 0px">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 style="text-align: center; font-family: lato">Start giving & receiving feedback</h2>
            </div>
            <div class="modal-body">

                <!-- start form body -->
                <div class="leads-modal">

                    <%= feature.name %>
                    <%= feature.company %>

                </div>
                <!-- end form body -->

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>

app/views/features/_form.html.erb
<%= simple_form_for(@feature, html: { class: "form-horizontal"}) do |f| %>
<%= f.error_notification %>

<div class="feature-header">
	<div id="title" style="text-align: center;line-height:1.2em">		
		We think great product ideas can come from anyone. Share yours today.
	</div>
	<div id="poster" style="text-align:center; margin-top: 10px">
		*if the company/app isn't on the list below, put it in the title/description, and we'll update it.
	</div>
</div>

<%= f.text_field :name, placeholder: "What's your idea?", class: "new-feature", :autocomplete => :off %>

<%= f.association :companies, :as => :collection_select, collection: Company.all.sort! { |a,b| a.name.downcase <=> b.name.downcase }, :input_html => { :class => "priority-selector" }, :label => false, prompt: "Company" %> 

<%= f.text_field :description, placeholder: "Tell us a bit more about the idea", class: "new-feature", :id => "new-feature-description", :autocomplete => :off %>

<%= f.input :priority, :collection => ['Bug','Feature','Redesign'], :label => false, :input_html => { :class => "priority-selector" }, :label => false, prompt: "Category" %>

<div class="new-feature">
	Add screenshots if you have them (up to 3)


	<%= f.input :shot1, label: false %>
	<%= f.input :shot2, label: false %> 
	<%= f.input :shot3, label: false %>
</div>
<div class="form-actions">
	<%= f.button :submit, class: "new-feature-button" %>
</div>
<% end %>

app/views/features/_indexsignedin.html.erb
<% if current_user.email.present? %>
<!-- blank space if email is present -->
<% else %>

<!-- start announcement if user is missing email -->
<div class="announcement">
    <p>Thanks for signing up! 1 more step.</p>
    <%= simple_form_for(current_user) do |f| %> 
    <table>
        <tr>
            <td>
                <%= f.text_field :email, label: false, placeholder: 'Enter your email', class: "email-form" %>
            </td>
            <td>

                <%= f.submit "Save", class: "email-button" %>
            </td>
        </tr>
    </table>
    <% end %>
</div>
<% end %>
<!-- end announcement if user is missing email -->


<!-- start printing of each feature -->
<% @features_days.keys.sort { |x,y| y <=> x }.each do |day| %>
<!-- If i add "sort_by" it seems to sort correctly on local but not on prod -->
<div class="feature-date">
    <%= day.time.to_s(:humanized_ago) %>
</div>
<% for feature in @features_days[day] %>
<div class='feature-box'>
    <div id="upvote-box">
        <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-arrow-up") + "", vote_feature_path(feature, type: "up"), method: "post" %>
        <br>
        <%= pluralize feature.reputation_for(:votes).to_i, "" %>
    </div>
    <div id="show-title">
        <a href="/features/<%= feature.id %>"><%= h truncate(feature.name, length: 65) %></a>
        <div id="show-company">
            <% Company.find(feature.company_ids).each do |c| %> 
            <a href="/companies/<%= c.id %>" target="_blank"><%= c.name %></a>
            <% end %>
        </div>
    </div>

    <!-- <div id="box-image">
        <%= image_tag User.find(feature.user_id).avatar(:medium) %>
    </div> -->

</div>
<% end %>
<% end %>
<!-- end printing of each feature -->
<br>

<div>
   <form action="/features/new">
      <input class="new-feature-button" type="submit" value="Post a feature">
  </form>
</div>

app/views/features/_indexsignedout.html.erb
<!-- start printing of each feature -->
<% @features_days.keys.sort { |x,y| y <=> x }.each do |day| %>
<!-- If i add "sort_by" it seems to sort correctly on local but not on prod -->
<div class="feature-date">
    <%= day.time.to_s(:humanized_ago) %>
</div>
<% for feature in @features_days[day] %>
<div class='feature-box'>
    <div id="upvote-box">
        <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-arrow-up") + "", 'auth/twitter' %>
        <br>
        <%= pluralize feature.reputation_for(:votes).to_i, "" %>
    </div>
    <div id="show-title">
        <a href="/features/<%= feature.id %>"><%= h truncate(feature.name, length: 65) %></a>
        <div id="show-company">
            <% Company.find(feature.company_ids).each do |c| %> 
            <a href="/companies/<%= c.id %>" target="_blank"><%= c.name %></a>
            <% end %>
        </div>
    </div>

    <!-- <div id="box-image">
        <%= image_tag User.find(feature.user_id).avatar(:medium) %>
    </div> -->

</div>
<% end %>
<% end %>
<!-- end printing of each feature -->
<br>

<div>
   <form action="/auth/twitter">
      <input class="new-feature-button" type="submit" value="Post a feature">
  </form>
</div>

app/views/features/_tweetflash.html.erb
<% if flash[:tweet_modal] %>
<% @company.each do |company| %>
<div class="tweet-flash">
    <i class="glyphicon glyphicon-thumbs-up"></i> Your vote was saved
    <br>
    <br>
    <button type="button" onclick=window.location="https://twitter.com/intent/tweet?text=.<%= company.twitter_nickname %>+I+just+voted+for+a+new+feature+on+@Feature_Hunt+via+featurehunt.com%2Ffeatures%2F<%= @feature.id %>" style="width:300px;height:50px;font-size:24px; background-color:white;color: rgba(159, 210, 250, 1.0); border: 1px solid white;border-radius: 100px">
        Tell <%= company.name %> about it</button>
    </div>
    <% end %>
	<% end %>

app/views/features/_upvoted.html.erb
<% Feature.evaluated_by(:votes, @user).sort.reverse { |a,b| a.created_at <=> b.created_at }.each do |feature| %>
<!-- Used this to order: http://stackoverflow.com/questions/11875174/rails-ordering-from-within-a-view -->

<div class='feature-box'>
    <div id="upvote-box">
        <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-arrow-up") + "", vote_feature_path(feature, type: "up"), method: "post" %>
        <br>
        <%= pluralize feature.reputation_for(:votes).to_i, "" %>
    </div>
    <div id="show-title">
        <a href="/features/<%= feature.id %>"><%= h truncate(feature.name, length: 65) %></a>
        <div id="show-company">
                        <% Company.find(feature.company_ids).each do |c| %> 
            <a href="/companies/<%= c.id %>" target="_blank"><%= c.name %></a>
            <% end %>
        </div>
    </div>

    <!-- <div id="box-image">
        <%= image_tag User.find(feature.user_id).avatar(:medium) %>
    </div> -->

</div>




<!-- feature Modal -->
<div class="modal fade" id="feature">
    <div class="modal-dialog">
        <div class="modal-content" style="border-radius: 0px">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 style="text-align: center; font-family: lato">Start giving & receiving feedback</h2>
            </div>
            <div class="modal-body">

                <!-- start form body -->
                <div class="leads-modal">

                    <%= feature.name %>
                    <%= feature.company %>

                </div>
                <!-- end form body -->

            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</div>


<% end %>

app/views/features/edit.html.erb
<h1>Editing <%= @feature.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<% if current_user %>
<%= render 'indexsignedin' %>

<!-- begin user not signed in -->
<% else %>

<%= render 'indexsignedout' %>

<!-- end user not signed in -->
<% end %>

app/views/features/new.html.erb
<%= render 'form' %>

app/views/features/show.html.erb
<%= render 'tweetflash' %>

<div class="feature-show">
    <div class="feature-header">
        <table>
            <tr>
                <td id="upvote-box" style="margin: 5px 20px 0px 4px; height: 65px; padding: 15px">

                    <%= link_to content_tag(:i, "", class: "glyphicon glyphicon-arrow-up") + "", vote_feature_path(@feature, type: "up"), method: "post" %>
                    <br>
                    <%= pluralize @feature.reputation_for(:votes).to_i, "" %>

                </td>
                <td>
                    <div id="title">
                        <%= @feature.name %>  <% if current_user == @feature.user %><%= link_to '(edit)', edit_feature_path(@feature) %><% end %>
                        <div id="company">
                            <% @company.each do |company| %>
                            <a href="/companies/<%= company.id %>" target="_blank"><%= company.name %></a>
                            <% end %>
                        </div>
                        <div id="poster">
                            posted by <a href="/users/<%= User.find(@feature.user_id).id %>"><%= User.find(@feature.user_id).nickname %></a> <%= time_ago_in_words(@feature.created_at) %> ago <% if @feature.priority.present? %>as a <button type="button" onclick=window.location='#' class="feature-priority">
                            <%= @feature.priority %>
                        </button>
                        <% end %>
                    </div>
                </div>
            </td>
        </tr>
    </table>
</div>
<div class="feature-shots">
    Description
</div>
<div id="feature-description">
    <%= @feature.description %>
</div>
<% if @feature.shot1.present? %>
<div class="feature-shots">
    Feature shots
</div>
<div class="feature-shots">
    <%= image_tag @feature.shot1(:medium), class: 'fancybox' %>
    <% if @feature.shot2.present? %>
    <%= image_tag @feature.shot2(:medium) %>
    <% end %>
    <% if @feature.shot3.present? %>
    <%= image_tag @feature.shot3(:medium) %>
    <% end %>
</div>
<% end %>
<%= render :partial => "comments/form" %>
<%= render :partial => "comments/comments" %>
</div>